spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/knowleadge?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    multipart:
      resolve-lazily: true
  data:
    elasticsearch:
      cluster-name: lgs-es
      cluster-nodes: 127.0.0.1:9300
      repositories:
      enabled: false #仓库中存储的数据
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:templates/ #模板加载路径 按需配置
